# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Testcase3' do
  before(:each) do
    @driver = Selenium::WebDriver.for(:remote, url: 'http://localhost:4444/wd/hub', desired_capabilities: Selenium::WebDriver::Remote::Capabilities.chrome)
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'testcase3' do
    # Test name: Testcase3
    # Step # | name | target | value
    # 1 | open | http://automationpractice.com/index.php?fbclid=IwAR1bkL0aKpUdKtLkjqDxBGacNSG9IojW3eAGr0-8NGx6Ykai6Uquc6FaVmI | 
    @driver.get('http://automationpractice.com/index.php?fbclid=IwAR1bkL0aKpUdKtLkjqDxBGacNSG9IojW3eAGr0-8NGx6Ykai6Uquc6FaVmI')
    # 2 | setWindowSize | 1042x813 | 
    @driver.manage.resize_to(1042, 813)
    # 3 | mouseOver | linkText=Sign in | 
    element = @driver.find_element(:link_text, 'Sign in')
    @driver.action.move_to_element(element).perform
    # 4 | click | linkText=Sign in | 
    @driver.find_element(:link_text, 'Sign in').click
    # 5 | click | css=#SubmitLogin > span | 
    @driver.find_element(:css, '#SubmitLogin > span').click
  end
end
